jobs:
  include:
  - stage: linter check
    language: node_js
    nodejs:
    - '10.11'
    install:
    - yarn install --production=false --frozen-lockfile
    script:
    - yarn lint
    cache: yarn

  - stage: Build docker images
    language: minimal
    services:
    - docker
    script:
    - docker build --build-arg API_KEY --build-arg API_URL -t $DOCKERHUB_OWNER/courier-monitoring-frontend:$TRAVIS_COMMIT -f Dockerfile .
    - docker tag $DOCKERHUB_OWNER/courier-monitoring-frontend:$TRAVIS_COMMIT $DOCKERHUB_OWNER/courier-monitoring-frontend:latest
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_NAME" --password-stdin
    - docker push $DOCKERHUB_OWNER/courier-monitoring-frontend
    if: branch = master
    branches:
      only:
      - master

  - stage: deploy
    name: kubernetes
    language: bash
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh $TRAVIS_COMMIT
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh $TRAVIS_COMMIT
      on:
        branch: develop
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_0159f993d050_key -iv $encrypted_0159f993d050_iv
      -in kubernetes.tar.enc -out ./kubernetes.tar -d
    - tar -xvf kubernetes.tar
    if: branch = master
    branches:
      only:
      - master
