jobs:
  include:
  - stage: linter check
    language: node_js
    nodejs:
    - '10.11'
    install:
    - yarn install --non-interactive --production=false --frozen-lockfile
    script:
    - yarn lint
    cache: yarn

  - stage: build
    language: node_js
    nodejs:
    - '10.11'
    install:
    - yarn install --non-interactive --production=false --frozen-lockfile
    script:
    - NODE_ENV=production yarn build
    cache: yarn
