export const REQUEST_COURIERS_BY_BOX_FIELD = 'REQUEST_COURIERS_BY_BOX_FIELD';
export const RECEIVE_COURIERS = 'RECEIVE_COURIERS';
export const RECEIVE_COURIERS_FAILED = 'RECEIVE_COURIERS_FAILED';

export const SHOW_COURIERS_LIST = 'SHOW_COURIERS_LIST';
export const HIDE_COURIERS_LIST = 'HIDE_COURIERS_LIST';

export const SHOW_COURIER_DETAILS = 'SHOW_COURIER_DETAILS';
export const HIDE_COURIER_DETAILS = 'HIDE_COURIER_DETAILS';
export const CLOSE_COURIER_DETAILS = 'CLOSE_COURIER_DETAILS';

export const PAN = 'PAN';

export const RECEIVE_GEO_HISTORY = 'RECEIVE_GEO_HISTORY';
export const RECEIVE_GEO_HISTORY_FAILED = 'RECEIVE_GEO_HISTORY_FAIL';

export const RECEIVE_ACTIVE_COURIER = 'RECEIVE_ACTIVE_COURIER';
export const RECEIVE_ACTIVE_COURIER_FAIL = 'RECEIVE_ACTIVE_COURIER_FAIL';
export const REQUEST_ACTIVE_COURIER = 'REQUEST_ACTIVE_COURIER';
export const RESET_ACTIVE_COURIER = 'RESET_ACTIVE_COURIER';
